'''
print ""
print ""
print ""
print "             __  __                 __      __       _    _    "
print "            |  \/  |__ _ _ _ _  _ __\ \    / /__ _ _| |__| |___"
print "            | |\/| / _` | ' \ || |___\ \/\/ / _ \ '_| / _` (_-<"
print "            |_|  |_\__,_|_||_\_, |    \_/\_/\___/_| |_\__,_/__/"
print "                             |__/                              "
print ""
print ""
print ""
'''
print "            .d.                                    .hdmmNNM-                                       .`                    "
print "           oMN                                     +MMMMMMM:                                      -MMNmhs+-              "
print "         .dMMm-                                    yMMMMMMM/               .----.                 +MMMMMMM+              "
print "  .-...:sNMMMMMNhs:`         -/                    NMMMMMMM+  -hhddmmmNm   hMMMMM-                sMMMMMMM.              "
print "+mmmMMMMMMMMMMMMMMMMy:  `.odMm.      -NNMMMM-     .MMMMMMMM+  oMMMMMMMMM.  hMMMMMd  +dmmNmoNNmmm/ hMMMMMMm               "
print " -mMMMMMMMMNhMMMMMMMMMmsNMMMN.       /MMMMMMh     +MMMMMMMMo  hMMMMMMMMM/  hMMMMMM+ sMMMMd+MMMMMo NMMMMMMs               "
print "  `hMMMMMMM/.NMMMMMMMMMMMMMN-        +MMMMMMM-    hMMMMMMMMs  NMMMMMMMMMy  hMMMMMMN.sMMMMy/MMMMMo`MMMMMMM-               "
print "    sMMMMMMMMMdNMMMMMNNMMMM+         +MMMMMMMh   `MMMMMMMMMs .MMMMMMMMMMN  hMMMMMMMhoMMMMs-MMMMMs:MMMMMMm                "
print "    .hMMMMMMMM/ .oMMm`.MMMM+         oMMMMMMMM:  :MMMMMMMMMs +MMMMMsMMMMM. hMMMMMMMMmMMMMo.MMMMMs+MMMMMMo                "
print "      +NMMMMMMMdmMMMMhNMMMMd         +MMMMMMMMd  sMMMMMMMMMy yMMMMN.MMMMM+ hMMMMMMMMMMMMM/`MMMMMysMMMMMM-                "
print "        +NMMMMMMMMMMMMMMMMMMy`       +MMMMMMMMM: mMMMMMMMMMy mMMMMMMMMMMMh hMMMMsNMMMMMMM: MMMMMyhMMMMMm                 "
print "         `yMMMMMMMMMMMMMMMMMMN/      +MMMMMMMMMd.MMMMMMMMMMy`MMMMMMMMMMMMN hMMMMosMMMMMMM- mMMMMhdMMMMMs                 "
print "           yMMMMMmdhhddmmmyo+//.     +MMMMMMMMMMhMMMMMMMMMMy:MMMMMo:yMMMMM-hMMMMo`NMMMMMM` hMMMMMMMMMMM-                 "
print "           /MMMN.                    +MMMMMMMMMMMMMMMMMMMMMyoMMMMM` :MMMMM/hMMMMo oMMMMMN  sMMMMMMMMMMm                  "
print "           :MMM/        -+`..``      oMMMMMMMMMMMMMMMdMMMMMhodddhs  `yyyyy:+syss: `syhhdy  `/sNMMMMMy/`                  "
print "           -MMN       ymMNoohmN`-    oMMMMMMhMMMMMMMdsMMMMMh                                  mMMMMM                     "
print "           -MMh    .ss/o.      :s.   oMMMMMM/dMMMMMM/sMMMMMh   .MMNNNNmmmmdddhhhhyyyyssss/    MMMMMM`                    "
print "           -MMs    oMN-    -..`      sMMMMMM::MMMMMm sMMMMMd   -MMMMMMMMMMMMMMMMMMMMMMMMMh   .MMMMMM.      .-:::.        "
print "           -MMo   .NMy     MMMMMNm+  sMMMMMM: dMMMM+ sMMMMMd   .MMMMMMMMMMMMMMMMMMMMMMMMMh   -MMMMMM-   /hNMMMMMMMds-    "
print "           -MMo    :s/     NMMMMMMy  sMMMmhs. .osys  /yyyyyo   `ssyyyyyyyyyyyyyyyyyyyyyyy+   :NNMMMM: .mMMMMMMMMMMMMMy   "
print "           :MMo    hMM:    mMMMMMMh  .-`    ::-..`      ...`                                     ``` `mMMMMMMMMMMMMMMMo  "
print "           /MMh     yMM/   hMMMMMMd  :hdNm `MMMMMM` .smMMMMMms.  /ossssyyyyyo-  .Nmmmdh.shhyyyyso:`  /MMMMMMMMoNMMMMMMs  "
print "           sMMN`    `+oo:  sMMMMMMm  dMMMM.`MMMMMM.+MMMMMMMMMMN- mMMMMMMMMMMMMd.-MMMMMM-mMMMMMMMMMMh.:MMMMMMMM/hMMMMMM/  "
print "          :NMMMh`     dMm  +MMMMMMN .MMMMM/ MMMMMM/MMMMMMMMMMMMh NMMMMMMMMMMMMMm-MMMMMM-mMMMMMMMMMMMM/NMMMMMMMy-+ydNMm   "
print "         -NMMMMMm+    .MM+ :MMMMMMM oMMMMMy MMMMMMoMMMMMM.MMMMMm`MMMMMM+NMMMMMMM:MMMMMM-mMMMMNsMMMMMMNsMMMMMMMM/    ``   "
print "       `yMMMMMMMMMN+   +o. .MMMMMMM`mMMMMMN MMMMMM+MMMMMM`MMMMMN.MMMMMMoNMMMMMMN-MMMMMM:mMMMMd:MMMMMMM:dMMMMMMMMs`       "
print "       mMMMMMMMMMMMMs  mMy `MMMMMMM+MMMMMMM-MMMMMM/MMMMMM`MMMMMN-MMMMMMMMMMMMMN:-MMMMMM:mMMMMhyMMMMMMM.`hMMMMMMMMm/      "
print "      `MMMMMMMMMMMMMm  NM+  NMMMMMMmMMMMMMMsMMMMMM:MMMMMM.MMMMMN:MMMMMMMMMMMNs. :MMMMMM-mMMMMMMMMMMMMo   /NMMMMMMMMd.    "
print "       mMMMMMMMMMMMMm `hh/  dMMMMMMMMMMMMMMNMMMMMM-MMMMMM.NMMMMm/MMMMMMmMMMMd   :MMMMMM-dMMMMMMMMMMm:  -- `oMMMMMMMMMo   "
print "       +MMMNMMMNMMMM: /my   yMMMMMMMMMMMMMMMMMMMMM-mMMMMM-NMMMMd+MMMMMM+MMMMMo  :MMMMMM-sddhhhyys+-`..-NMmo`.dMMMMMMMMy  "
print "       mMMhmMMyMMMd -NN:   /MMMMMMMMMMMMMMMMMMMMM-dMMMMM.NMMMMhoMMMMMM.MMMMMN. :MMMMMMsssyyhddmNMMMModMMMMMy-hMMMMMMMMo  "
print "        :MMN+MmoMMM/`+y+    .MMMMMMMMMNNMMMMMMMMMM-sMMMMMNMMMMMssMMMMMM`hMMMMMh -MMMMMMMMMMMMMMMMMMMM:MMMMMMMm.MMMMMMMMM`"
print "         hMM+MMsMMm+MN-      MMMMMMMMM:oMMMMMMMMMM-`mMMMMMMMMMm.yMMMMMM`oMMMMMM/-MMMMMMMMMMMMMMMMMMMM/MMMMMMMh`MMMMMMMMM-"
print "         .MMydNyMMoNh`       mMMMMMMM/ `NMMMMMMMMM-  /ymMMMmh/  hMMMMMM`:MMMMMMN.yyssssssssssssooo++//MMMMMMMNsMMMMMMMMM."
print "       .ssMNsNhMNos`        hMMMMMM+   +MMMMMMMMM-                     `MMMMMMMs                    .MMMMMMMMMMMMMMMMMm  "
print "       :MMoNMsmhMoNM:        /syhdmo     mMMMMMMMM-                      dMMMMMMM-                    yMMMMMMMMMMMMMMMM: "
print "       -MMNyMydhNsMMo                    /MMMMMMMM.                      oMMMMMMMd                     hMMMMMMMMMMMMMN:  "
print "         /hdhMssmNdho`                     hNMMMMMM.                      -MMMMMMMM+                     :hMMMMMMMMMmo`  "
print "         `:.`  `.:`                          ``...                        dNMMMMMMN`                      `-/+oo+:.      "
print "                                                                             `..--`                                      "
